### ISSUE TITLE
@Profile with SpringBootMongock

### ISSUE THREAD

**Issue by LeJeanbono** [cloudyrock/mongock#81] opened 2019-08-02 14:37 UTC
Hi,
I configured SpringBootMongock like : 

```java
@Bean
    public SpringBootMongock mongock(ApplicationContext springContext, MongoClient mongoClient, MongoProperties mongoProperties) {
        return new SpringBootMongockBuilder(mongoClient, mongoProperties.getDatabase(), "my.package")
                .setApplicationContext(springContext)
                .setLockQuickConfig()
                .build();
    }
```
And ChangeLog : 
```java
@ChangeLog
@Profile({"!test", "!dataset"})
public class DatabaseChangelog {
...
}
```

When I'm running tests with `@ActiveProfiles("test")`, Mongock is executed.
Method `.setSpringEnvironment(environment)` of `SpringMongock` is not implemented in `SpringBootMongock`
Did I miss something to handle my profile ?

**Comment by dieppa** [comment] 2019-08-02 14:50
Hi @LeJeanbono , which version are you using?
We'll have a look, you can expect to have an answer on Monday morning as latest ;)

**Comment by LeJeanbono** [comment] 2019-09-03 15:40
Sorry, was on holidays :)
I'm using `com.github.cloudyrock.mongock:mongock-spring:2.0.2`

**Comment by dieppa** [comment] 2019-09-03 15:43
good, we'll have a look at that and will try to reproduce it and introduce the fix in the 3.0.3.BETA.

**Comment by LeJeanbono** [comment] 2019-09-10 19:11
Do you need more informations ?

**Comment by dieppa** [comment] 2019-09-10 20:07
Hello, sorry, we am on vacations now. I will be back at the end of the week. Sorry for the inconvenient.

**Comment by dieppa** [comment] 2019-09-23 18:21
Hello @LeJeanbono , sorry but we are a bit busy. Do you need this urgently or it can wait?

**Comment by LeJeanbono** [comment] 2019-09-23 19:36
It's not critical, just a lost of time during testing.
Do you have an idea of the problem ?
I can do a MR

**Comment by dieppa** [comment] 2019-09-23 19:42
I haven't looked at it yet, but it seems that SpingBootMongock is not taking the profile into account, which it's easy to fix. If you want to give a shoot, I am happy to review it

**Comment by LeJeanbono** [comment] 2019-10-29 20:20
I took a look, for me, all should work.
Can you have a look please ?

**Comment by dieppa** [comment] 2019-10-29 20:38
hello @LeJeanbono , you mean a PR? I don't see anything. But I will have a look once your PR is raised ;)

**Comment by LeJeanbono** [comment] 2019-10-29 20:55
I didn't find the problem, can't do a PR :/

**Comment by dieppa** [comment] 2019-10-29 21:44
aah sorry, I misunderstood. I will, thanks

**Comment by dieppa** [comment] 2019-11-07 08:24
I am looking at this. I hope to have some news soon.

**Comment by dieppa** [comment] 2019-11-07 09:21
Hello again, released 3.0.6.BETA version with the fix. 
Still no merged to master as I want to add some tests and get your feedback, but should be fine.

Please let me know if works for you, so I can close this issue.

Thanks @LeJeanbono

**Comment by dieppa** [comment] 2019-11-07 09:43
@LeJeanbono , while that fix should work for you. It's definitive. I am  going adapt it to the Spring 5.1 way, with profile string, with !,&,|. 
I will keep you updated.

**Comment by LeJeanbono** [comment] 2019-11-07 13:20
@dieppa Thank you, I just make some tests and it seems to be ok :)

**Comment by dieppa** [comment] 2019-11-07 14:43
thanks, I close this

**Comment by LeJeanbono** [comment] 2019-11-13 15:26
Hi @dieppa in `  private boolean matchesActiveSpringProfile(AnnotatedElement element) {` your fix will return false if we only have the `default` Profile

**Comment by dieppa** [comment] 2019-11-25 18:02
Sorry, I am just seeing this.

Yeah, good point. I will look at that this week and I promise I will have a new release at the of it(at most)

**Comment by dieppa** [comment] 2019-12-17 19:00
Hi @LeJeanbono ,
sorry for the delay. Can you provide an example when it returns false with default profile? I am probably missing something, but don't see it

**Comment by LeJeanbono** [comment] 2019-12-17 19:57
Hey @dieppa !
When `activeProfiles` is `default` (No` @Profile `set on the class), the method return `false` because  `default` is not in profile list : https://github.com/cloudyrock/mongock/blob/b3b0198c0e48df563670c84f709d6a776616c755/mongock-spring/src/main/java/com/github/cloudyrock/mongock/SpringChangeService.java#L72`

**Comment by dieppa** [comment] 2019-12-17 20:10
Hey! thanks for your quick answer.
Have you tested it? Because I did and it returns true because of this [line](https://github.com/cloudyrock/mongock/blob/b3b0198c0e48df563670c84f709d6a776616c755/mongock-spring/src/main/java/com/github/cloudyrock/mongock/SpringChangeService.java#L60).

Unless I am missing something

**Comment by LeJeanbono** [comment] 2019-12-17 20:36
Yep
Keep `@Profile({"!test", "!dataset"})` and run Spring without profile : Mongock will not work.

**Comment by dieppa** [comment] 2019-12-17 20:37
cool, that what I needed 👍

**Comment by dieppa** [comment] 2019-12-18 16:29
Hello @LeJeanbono ,
3.0.7.BETA has been released with the profile fixed. I close this, but let me know when you are able to test it.

You can see the tests  we've added in [SpringChangeServiceTest](https://github.com/cloudyrock/mongock/blob/master/mongock-spring/src/test/java/com/github/cloudyrock/mongock/SpringChangeServiceTest.java)

**Closed** 2019-12-18 16:29 UTC
