### ISSUE TITLE
Use mongock with springboot 2.0.7 but do not work

### ISSUE THREAD

**Issue by sgrillon14** [cloudyrock/mongock#53] opened 2018-12-13 07:58 UTC
I copy/pase your sample:

```
@Bean
public SpringBootMongock mongock(ApplicationContext springContext, MongoClient mongoClient) {
  return new SpringBootMongockBuilder(mongoClient, "yourDbName", "com.package.to.be.scanned.for.changesets")
      .setApplicationContext(springContext) 
      .setLockQuickConfig()
      .build();
}
```

but I need add a cast:

```
@Bean
public SpringBootMongock mongock(ApplicationContext springContext, MongoClient mongoClient) {
  return (SpringBootMongock) new SpringBootMongockBuilder(mongoClient, "yourDbName", "com.package.to.be.scanned.for.changesets")
      .setApplicationContext(springContext) 
      .setLockQuickConfig()
      .build();
}
```

and after I had this problem:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongock' defined in class path resource [com/myproject/user/configuration/MongoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.SpringBootMongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at com.myproject.user.UserServerApplication.main(UserServerApplication.java:19) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.SpringBootMongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyClass(ProxyFactory.java:58) ~[mongock-core-1.16.1.jar:na]
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyFromOriginal(ProxyFactory.java:99) ~[mongock-core-1.16.1.jar:na]
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.build(SpringBootMongockBuilder.java:80) ~[mongock-spring-1.16.1.jar:na]
	at com.github.cloudyrock.mongock.SpringBootMongockBuilder.build(SpringBootMongockBuilder.java:15) ~[mongock-spring-1.16.1.jar:na]
	at com.myproject.user.configuration.MongoConfiguration.mongock(MongoConfiguration.java:35) ~[classes/:na]
	at com.myproject.user.configuration.MongoConfiguration$$EnhancerBySpringCGLIB$$cc3decd7.CGLIB$mongock$0(<generated>) ~[classes/:na]
	at com.myproject.user.configuration.MongoConfiguration$$EnhancerBySpringCGLIB$$cc3decd7$$FastClassBySpringCGLIB$$c35f50f6.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at com.myproject.user.configuration.MongoConfiguration$$EnhancerBySpringCGLIB$$cc3decd7.mongock(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[cglib-3.2.7.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) ~[cglib-3.2.7.jar:na]
	... 34 common frames omitted

```

**Comment by dieppa** [comment] 2018-12-13 08:21
Hello @sgrillon14. Please, can you tell me which version of Mongock you are using?
For future issues, please use this [template](https://github.com/cloudyrock/mongock/blob/master/community/ISSUE_TEMPLATE.md)

**Comment by sgrillon14** [comment] 2018-12-13 08:47
```
    <dependency>
          <groupId>com.github.cloudyrock.mongock</groupId>
          <artifactId>mongock-core</artifactId>
          <version>1.16.1</version>
    </dependency>
    <dependency>
          <groupId>com.github.cloudyrock.mongock</groupId>
          <artifactId>mongock-spring</artifactId>
          <version>1.16.1</version>
    </dependency>
```

**Comment by dieppa** [comment] 2018-12-13 08:49
You don't need to import both. Try importing only spring, and let me know how it goes ;)

**Comment by sgrillon14** [comment] 2018-12-13 08:54
same issue with `mongock-spring` only

**Comment by dieppa** [comment] 2018-12-13 09:02
@sgrillon14 I have several projects using Mongock in production, but those projects are private, so I cannot share it.

However, we will have a look to this today and I will update you and we will try to provide some sample projects, as I believe it's a good idea.

**I will use Spring-boot 2.0.7, a y other requirement you think could affect?**

**Comment by sgrillon14** [comment] 2018-12-13 09:33
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>

**Comment by dieppa** [comment] 2018-12-13 10:43
@sgrillon14  let me know if the temporal workaround works for you

**Comment by sgrillon14** [comment] 2018-12-13 11:05
I try use Mongock in a more simple projet. I looking for where from `MongoDatabase db` of `public void someChange2(MongoDatabase db) {`

I think in auto-configuration of `spring-boot-starter-data-mongodb` but I have this:

```
***************************
APPLICATION FAILED TO START
***************************
Description:
A component required a bean of type 'com.mongodb.client.MongoDatabase' that could not be found.
Action:
Consider defining a bean of type 'com.mongodb.client.MongoDatabase' in your configuration.
```

**Comment by dieppa** [comment] 2018-12-13 11:09
Yeah,  I was about to send you a message as we spotted some other problem using Spring boot 2.0.7 with MongoDatabase. Not that one tho.

Anyway, we are working on it and we expect to deploy a fix today. We'll keep you updated.

**Comment by dieppa** [comment] 2018-12-13 13:44
@sgrillon14 we have fixed the [issue](https://github.com/cloudyrock/mongock/issues/55) with MongoDatabase. 

We created [project](https://github.com/cloudyrock/springboot-2-0-7-sample) where you can see how to use it. Please notice, it uses a branch which hasn't been released yet. please checkout locally the project first by doing:

1.  git clone https://github.com/cloudyrock/mongock.git
2. git checkout issue/55
3. mvn clean install

Then you can run the [sample project](https://github.com/cloudyrock/springboot-2-0-7-sample)

Please let us know how it goes. We are working on fixing the Spring boot module issue.

**Comment by sgrillon14** [comment] 2018-12-13 14:50
How to use `mongoTemplate` in a `ChangeSet`?

```
   @ChangeSet(id= "cs-1", order = "001", author = "mongock")
    public void changeSet1(MongoTemplate mongoTemplate) {
       User admin = new User("admin", "admin");
       admin.getRoles().add("ADMIN");
       mongoTemplate.save(admin, "user");
    }
```

**Comment by dieppa** [comment] 2018-12-13 15:11
Yeah. Mongodatabase is fixed but not released. And yes, we'll try to have the template issue with springboot 2.0.7 as soon as possible. Hopefully today, otherwise tomorrow. We'll keep you updated

**Comment by sgrillon14** [comment] 2018-12-13 15:13
great thanks a lot

**Comment by dieppa** [comment] 2018-12-13 21:09
@sgrillon14 the sample has been updated. It uses mongock-spring version 2.0.0-BETA and works fine.
Please, have a look to the [sample](https://github.com/cloudyrock/springboot-2-0-7-sample).

Please notice, version 2.0.0-BETA stills have the bug with MongoDatabase recently fixed  and released in version 1.16.2. This fix will be added to 2.0.1 and released soon. Hopefully tomorrow evening UK time.

**Comment by sgrillon14** [comment] 2018-12-14 09:46
I have a look to the sample but you do not push the fix on 2.0.0-BETA and 1.16.2. 

```
protected void executeChangeSetMethod(Method changeSetMethod, Object changeLogInstance)
      throws IllegalAccessException, InvocationTargetException {
    if (changeSetMethod.getParameterTypes().length == 1
        && changeSetMethod.getParameterTypes()[0].equals(DB.class)) {
      logger.debug("method with DB argument");

      changeSetMethod.invoke(changeLogInstance, this.changelogDb);
    } else if (changeSetMethod.getParameterTypes().length == 1
        && changeSetMethod.getParameterTypes()[0].equals(MongoDatabase.class)) {
      logger.debug("method with MongoDatabase argument");

      changeSetMethod.invoke(changeLogInstance, this.changelogMongoDatabase);
    } else if (changeSetMethod.getParameterTypes().length == 0) {
      logger.debug("method with no params");

      changeSetMethod.invoke(changeLogInstance);
    } else {
      throw new MongockException("ChangeSet method " + changeSetMethod.getName() +
          " has wrong arguments list. Please see docs for more info!");
    }
  }
```

I have this:

`ERROR 18560 --- [           main] com.github.cloudyrock.mongock.Mongock    : ChangeSet method createAdmin has wrong arguments list. Please see docs for more info!`

**Comment by dieppa** [comment] 2018-12-14 09:50
No, I didnt need to do anything the sample project with spribgboot 2.0.7 and Mongock 2.0.0-BETA just work.


Pleqse havr a look to the sample and try to spot yhe difference. Alternativaly, guve me access to your project or create a similar one with the same issue, so I can download it and see what is going on

**Comment by sgrillon14** [comment] 2018-12-14 09:59
OK, the sample work, I looking for the diff.

**Comment by sgrillon14** [comment] 2018-12-14 14:46
I add this repository:

https://github.com/sgrillon14/springboot-2-0-7-sample/blob/master/src/main/java/com/github/cloudyrock/mongock/springboot207sample/changesets/ClientChangeLog.java

**Comment by sgrillon14** [comment] 2018-12-14 15:15
I can help you, where is branch version 2.0.0-BETA?

**Comment by dieppa** [comment] 2018-12-14 15:20
@sgrillon14 that error your are getting relating MongoDatabase is what was fixed in version 1.16.2. So don't worry it will be added to 2.0.0-BETA. You can actually see the fix in the new changelog file we have added.

On the other hand, 2.0.0-BETA is a external pull request from @engan81. We are waiting for him to rebase from master to approve the PR. You can see it [here](https://github.com/cloudyrock/mongock/pull/45)

**Comment by sgrillon14** [comment] 2018-12-14 15:38
I need using both. Whith MongoDatabase I add any index in my document and after I use MongoTemplate for the CRUD.

I wait 1.16.2 release and after I close this issue.

great thanks a lot

**Comment by dieppa** [comment] 2018-12-14 15:42
Cool, so I can tell you with confidence you will have a version released today ;)

**Comment by dieppa** [comment] 2018-12-14 21:04
Fixed in PR #45

**Closed** 2018-12-14 21:04 UTC
Labels: bug, spring-module

**Comment by dieppa** [comment] 2018-12-14 21:31
@sgrillon14 as you may have noticed, new 2.0.0 version has been released with MongoDatabase fix and Spring 5./Springboot2.x support.

Please have a try and let me know how it goes.

Thanks

**Comment by sgrillon14** [comment] 2018-12-17 16:30
in the simple project is it OK but in my complex project I have this (I do not find the difference):

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongock' defined in class path resource [com/myproject/user/configuration/MongoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.Mongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:591) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.7.RELEASE.jar:2.0.7.RELEASE]
	at com.myproject.user.UserServerApplication.main(UserServerApplication.java:21) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.cloudyrock.mongock.Mongock]: Factory method 'mongock' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyClass(ProxyFactory.java:59) ~[classes/:na]
	at com.github.cloudyrock.mongock.ProxyFactory.createProxyFromOriginal(ProxyFactory.java:105) ~[classes/:na]
	at com.github.cloudyrock.mongock.SpringMongockBuilder.build(SpringMongockBuilder.java:101) ~[classes/:na]
	at com.github.cloudyrock.mongock.SpringMongockBuilder.build(SpringMongockBuilder.java:13) ~[classes/:na]
	at com.myproject.user.configuration.MongoConfiguration.mongock(MongoConfiguration.java:34) ~[classes/:na]
	at com.myproject.user.configuration.MongoConfiguration$$EnhancerBySpringCGLIB$$f0c9d13b.CGLIB$mongock$0(<generated>) ~[classes/:na]
	at com.myproject.user.configuration.MongoConfiguration$$EnhancerBySpringCGLIB$$f0c9d13b$$FastClassBySpringCGLIB$$c0ae7ef0.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365) ~[spring-context-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	at com.myproject.user.configuration.MongoConfiguration$$EnhancerBySpringCGLIB$$f0c9d13b.mongock(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.11.RELEASE.jar:5.0.11.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-5.0.4.jar:5.0.4]
	at net.sf.cglib.core.DebuggingClassWriter.<init>(DebuggingClassWriter.java:49) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.DefaultGeneratorStrategy.getClassVisitor(DefaultGeneratorStrategy.java:30) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:24) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54) ~[cglib-3.2.7.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:174) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:153) ~[cglib-3.2.7.jar:na]
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73) ~[cglib-3.2.7.jar:na]
	... 34 common frames omitted
```

**Comment by dieppa** [comment] 2018-12-17 16:53
I will have a look.

**Comment by dieppa** [comment] 2018-12-17 16:59
Can you confirm which version of mongock-spring you are using? 
And what you have in in your ProxyFactory.java:59(mongock class). It doesn't make sense that line is failing in the cod eI have

**Comment by sgrillon14** [comment] 2018-12-18 08:47
I use version 2.0.1-SNAPSHOT

59 Enhancer enhancer = new Enhancer() {
60      @Override
61      protected void filterConstructors(Class sc, List constructors) {
62        //Ignoring filter filter
63      }
64    };

**Comment by dieppa** [comment] 2018-12-18 08:57
First, why aren't you using the released version 2.0.0?
 Second, that's is pretty weird as that line just creates a new Enhancer, so unless you have some library in your classpath that is messing that, shouldn't have problem.

So in order to help you ideally you can share the project with me so I can debug it. If that is not possible, because is private, you can share with your pom, so I can try to reproduce that.

Without that there is not much I can do as you can see the sample project works fine and I can confirm there are some other people using version 2.0.0 with no issue.

**Comment by sgrillon14** [comment] 2018-12-18 12:56
I find the problem:

`spring-cloud-starter-netflix-hystrix` import  odl version of asm, so I exclude this

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
            <exclusions>
            <exclusion>
             <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
            </exclusion>
            </exclusions>
        </dependency>
```

**Comment by sgrillon14** [comment] 2018-12-18 13:06
I confirm that version 2.0.0 is ready for use in production :+1:

**Comment by dieppa** [comment] 2018-12-18 13:15
Great, thanks @sgrillon14

**Comment by erkieh** [comment] 2019-06-01 16:56
I got a similar problem
spring-boot-starter-test->json-path->json-smart->accessors-smart pulls in asm:5.0.4

**Comment by dieppa** [comment] 2019-06-03 07:17
@erkieh  have you tried to exclude it?

**Comment by erkieh** [comment] 2019-06-03 08:00
Yes, it works when I exclude it.

**Comment by dieppa** [comment] 2019-06-03 08:07
is it that fine?
