### ISSUE TITLE
Problem with replaceOne with upsert

### ISSUE THREAD

**Issue by grabarczyk-t** [cloudyrock/mongock#90] opened 2019-10-01 08:00 UTC
I have a problem using `MongoCollection.replaceOne` method in Mongock ChangeSet methods. When I do something like this:

```
@ChangeSet(id = "test-replace", order = "001")
public void testReplace(MongoDatabase db) {
	MongoCollection<Document> testCollection = db.getCollection("TestCollection");
	Document testDocument = new Document("_id", "testId").append("testField", "testValue");
	testCollection.replaceOne(eq("_id", "testId"), testDocument, 
		ReplaceOptions.createReplaceOptions(new UpdateOptions().upsert(true)));
}
```

I get an exception:

```
[INFO] Caused by: java.lang.reflect.InvocationTargetException: null
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at com.github.cloudyrock.mongock.SpringBootMongock.executeChangeSetMethod(SpringBootMongock.java:66)
[INFO] 	at com.github.cloudyrock.mongock.Mongock.executeIfNewOrRunAlways(Mongock.java:128)
[INFO] 	at com.github.cloudyrock.mongock.Mongock.executeMigration(Mongock.java:112)
[INFO] 	... 176 common frames omitted
[INFO] Caused by: java.lang.AbstractMethodError: Method com/github/cloudyrock/mongock/decorator/impl/MongoCollectionDecoratorImpl.replaceOne(Lorg/bson/conversions/Bson;Ljava/lang/Object;Lcom/mongodb/client/model/ReplaceOptions;)Lcom/mongodb/client/result/UpdateResult; is abstract
[INFO] 	at com.github.cloudyrock.mongock.decorator.impl.MongoCollectionDecoratorImpl.replaceOne(MongoCollectionDecoratorImpl.java)
[INFO] 	at pl.test.TestMigrations.testReplace(TestMigrations.java:33)
[INFO] 	... 183 common frames omitted
```

The line that the exception points to (TestMigrations.java:33) is the line with `testCollection.replaceOne` method

This error occurs only when I am using replaceOne with upsert, when I use replaceOne without ReplaceOptions the migration runs without problem.

I am using com.github.cloudyrock.mongock:mongock-spring in version 3.0.3.BETA

**Comment by dieppa** [comment] 2019-10-01 08:15
Thanks @grabarczyk-t . We'll have a look today or tomorrow an will update you. It seems easy to reproduce and fix.

Thanks

**Comment by dieppa** [comment] 2019-10-01 18:46
Hello @grabarczyk-t ,

if you see Mongock is using  mongodb driver 3.6, and the method you are invoking is since 3.7.

That can be updated at the end of this week. Meanwhile You can use the deprecated method which is exactly the same but using UpdateOptions, rather than ReplaceOptions, and update your code once Mongock is updated.

<img width="764" alt="Screenshot 2019-10-01 at 19 42 42" src="https://user-images.githubusercontent.com/19335433/65990603-cf395300-e483-11e9-8382-c2742eef9ff8.png">

**Comment by grabarczyk-t** [comment] 2019-10-02 07:02
Ok, thanks!

**Comment by earandap** [comment] 2019-10-08 18:52
I have the same issue.

**Comment by dieppa** [comment] 2019-10-08 18:56
It makes senses, as the issue is due to mongoDriver versions. Spring boot uses 3.7 and Mongock 3.5. We are pretty busy, finding the time to update it(it\s not just change the version in the pom ;D )

**Comment by dieppa** [comment] 2019-10-18 17:52
Hello @grabarczyk-t  and @earandap ,

sorry for the delay, but we have been pretty busy private projects. It has been released version 3.0.4.BETA which has MongoDB driver updated to 3.11.0.
This should solve your issue.

Please let me know if this does the job.

`
<dependency>
<groupId>com.github.cloudyrock.mongock</groupId>
<artifactId>mongock-core</artifactId>
<version>3.0.4.BETA</version>
</dependency>
`

**Comment by grabarczyk-t** [comment] 2019-10-21 10:23
Hi,

Thanks for the update. I checked if this fixes this issue, and now the changeset method passes without errors, however it doesn't seem to work as it should. I tried running the code I have written in the first post, and when I run it outside mongock context - just manually creating MongoTemplate - it adds the document to the database properly, and when I run mongock with this ChangeSet the document is not added. In both cases I had empty database before the run.

**Comment by dieppa** [comment] 2019-10-21 10:47
interesting, We'll have a look. We had deactivate temporally tests because of Fongo incompatibility with new MongoDB driver version.

Cheers

**Comment by dieppa** [comment] 2019-10-22 09:45
@grabarczyk-t , sorry, just to keep you updated. I will try to reproduce your issue myself this evening. I will try to have something for tomorrow or after tomorrow.

Thanks for your patience

**Comment by grabarczyk-t** [comment] 2019-10-22 09:51
Thanks for your being so considerate. Don't worry, I don't need this issue fixed that urgently.

**Comment by abhishekshah2905** [comment] 2019-10-29 07:25
+1

**Comment by dieppa** [comment] 2019-10-29 23:35
Sorry guys, have been really busy. Anyway, that was a very silly issue, which is already fixed in version 3.0.5.BETA

Please, I'd really appreciate if you can confirm it's fixed @grabarczyk-t , @abhishekshah2905 , @earandap 

Thanks

**Comment by abhishekshah2905** [comment] 2019-10-31 03:03
@dieppa 

It's fixed for now. Thank you for the quick action.

**Comment by dieppa** [comment] 2019-10-31 07:27
👍  I close this

**Closed by dieppa** 2019-10-31 07:27 UTC
